highlighter: rouge
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 4000
safe: true
url: http://biomadeira.github.io/vitae
author: Fábio Madeira

# edit this section with your information
# biomadeira.github.io - all contents run on /vitae/
# for a normal use at the base of the server change it to "/"
baseurl: /vitae/
title: Ryan Stewart's CV
name: "Ryan Stewart, DO"
email: ryan@ryanstewart.com
email_full: mailto:ryan@ryanstewart.com
website: github.io/stuboo
website_full: https://stuboo.github.io/vitae
github: stuboo
twitter: stuboo
tel: +1 865 238 4224
tel_full: tel:+18652384224
google_maps: 'https://www.google.com/maps/@38.2327116,-85.736552,11z'
address: "Beautiful &amp; Scenic"
#postcode: EH3 5BL
city: "Louisville, KY"
#country: United Kingdom
#google_analytics: UA-69300817-1

# needed for travis-ci build
exclude: [vendor]
